// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: plan-feature.proto

package plan_feature

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plan    string `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Feature string `protobuf:"bytes,2,opt,name=feature,proto3" json:"feature,omitempty"`
}

func (x *AllowedRequest) Reset() {
	*x = AllowedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plan_feature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedRequest) ProtoMessage() {}

func (x *AllowedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plan_feature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedRequest.ProtoReflect.Descriptor instead.
func (*AllowedRequest) Descriptor() ([]byte, []int) {
	return file_plan_feature_proto_rawDescGZIP(), []int{0}
}

func (x *AllowedRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *AllowedRequest) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

type AllowedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
}

func (x *AllowedResponse) Reset() {
	*x = AllowedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plan_feature_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedResponse) ProtoMessage() {}

func (x *AllowedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plan_feature_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedResponse.ProtoReflect.Descriptor instead.
func (*AllowedResponse) Descriptor() ([]byte, []int) {
	return file_plan_feature_proto_rawDescGZIP(), []int{1}
}

func (x *AllowedResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_plan_feature_proto protoreflect.FileDescriptor

var file_plan_feature_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6c, 0x61, 0x6e, 0x2d, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x32, 0x53,
	0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x6e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x44, 0x0a,
	0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2d, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plan_feature_proto_rawDescOnce sync.Once
	file_plan_feature_proto_rawDescData = file_plan_feature_proto_rawDesc
)

func file_plan_feature_proto_rawDescGZIP() []byte {
	file_plan_feature_proto_rawDescOnce.Do(func() {
		file_plan_feature_proto_rawDescData = protoimpl.X.CompressGZIP(file_plan_feature_proto_rawDescData)
	})
	return file_plan_feature_proto_rawDescData
}

var file_plan_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plan_feature_proto_goTypes = []interface{}{
	(*AllowedRequest)(nil),  // 0: planFeature.AllowedRequest
	(*AllowedResponse)(nil), // 1: planFeature.AllowedResponse
}
var file_plan_feature_proto_depIdxs = []int32{
	0, // 0: planFeature.PlanFeature.Allowed:input_type -> planFeature.AllowedRequest
	1, // 1: planFeature.PlanFeature.Allowed:output_type -> planFeature.AllowedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plan_feature_proto_init() }
func file_plan_feature_proto_init() {
	if File_plan_feature_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plan_feature_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plan_feature_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plan_feature_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plan_feature_proto_goTypes,
		DependencyIndexes: file_plan_feature_proto_depIdxs,
		MessageInfos:      file_plan_feature_proto_msgTypes,
	}.Build()
	File_plan_feature_proto = out.File
	file_plan_feature_proto_rawDesc = nil
	file_plan_feature_proto_goTypes = nil
	file_plan_feature_proto_depIdxs = nil
}
